<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Include PHPMailer
require '../phpmailer/src/Exception.php';
require '../phpmailer/src/PHPMailer.php';
require '../phpmailer/src/SMTP.php';

// Include FPDF
require_once __DIR__ . '/fpdf/fpdf.php';

// Check if form submitted
if ($_SERVER["REQUEST_METHOD"] == "POST") {

    // Get form data safely
    $name    = $_POST['name'] ?? '';
    $email   = $_POST['email'] ?? '';
    $subject = $_POST['subject'] ?? '';
    $address = $_POST['address'] ?? '';

    // ---------- 1️⃣ Create PDF ----------
    class PDF extends FPDF {
        function Header() {
            // Add logo (optional)
            if (file_exists(__DIR__ . '/assets/logo.png')) {
                $this->Image(__DIR__ . '/assets/logo.png', 10, 6, 25);
            }

            // Header background
            $this->SetFillColor(0, 102, 204); // blue
            $this->Rect(0, 0, 210, 25, 'F');

            // Title
            $this->SetFont('Arial', 'B', 20);
            $this->SetTextColor(255, 255, 255);
            $this->Cell(0, 15, 'Contact Form Submission', 0, 1, 'C');
            $this->Ln(10);
        }

        function Footer() {
            // Footer text
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->SetTextColor(128);
            $this->Cell(0, 10, 'Generated by Ayushi Project • ' . date('Y-m-d H:i:s'), 0, 0, 'C');
        }

        function FancyTable($data) {
            // Table header color
            $this->SetFillColor(230, 230, 250);
            $this->SetDrawColor(180, 180, 180);
            $this->SetTextColor(0);
            $this->SetFont('Arial', 'B', 12);

            $this->Cell(60, 10, 'Field', 1, 0, 'C', true);
            $this->Cell(130, 10, 'Value', 1, 1, 'C', true);

            $this->SetFont('Arial', '', 12);

            // Loop through data
            foreach ($data as $key => $value) {
                $this->Cell(60, 10, $key, 1, 0, 'L');
                $this->MultiCell(130, 10, $value, 1, 'L');
            }
        }
    }

    // Create PDF
    $pdf = new PDF();
    $pdf->AddPage();

    // Intro text
    $pdf->SetFont('Arial', '', 12);
    $pdf->MultiCell(0, 10, "Below are the details submitted through the contact form:", 0, 'L');
    $pdf->Ln(5);

    // Table Data
    $data = [
        'Name'    => $name,
        'Email'   => $email,
        'Subject' => $subject,
        'Address' => $address
    ];

    // Add table
    $pdf->FancyTable($data);

    $pdf->Ln(10);
    $pdf->SetFont('Arial', 'I', 11);
    $pdf->Cell(0, 10, 'Thank you for contacting us! We will get back to you soon.', 0, 1, 'C');

    // Save the file
    $file = __DIR__ . '/contact_details.pdf';
    $pdf->Output($file, 'F');

    // ---------- 2️⃣ Send Email with PHPMailer ----------
    $mail = new PHPMailer(true);

    try {
        // SMTP Config
        $mail->isSMTP();
        $mail->Host       = 'smtp.gmail.com';
        $mail->SMTPAuth   = true;
        $mail->Username   = 'aayupatel782@gmail.com';   // 🔹 Your Gmail
        $mail->Password   = 'joufesdiignmpzio';      // 🔹 Your App Password
        $mail->SMTPSecure = 'tls';
        $mail->Port       = 587;

        // Sender & Recipients
        $mail->setFrom('aayupatel782@gmail.com', 'Ayushi Project');
        $mail->addAddress($email, $name); // Send to user
        $mail->addAddress('your_email@gmail.com');    // Optional: copy to yourself

        // Attach PDF
        $mail->addAttachment($file);

        // Email Content
        $mail->isHTML(true);
        $mail->Subject = "Contact Form Details from $name";
        $mail->Body = "
            <h2 style='color:#0066cc;'>Hello $name 👋</h2>
            <p>Thank you for contacting us! Please find your submitted details attached in PDF format.</p>
            <p><strong>Subject:</strong> $subject<br>
            <strong>Address:</strong> $address</p>
            <p>We'll reach out to you soon!</p>
            <br>
            <p style='font-size:12px;color:#777;'>Best Regards,<br><b>Ayushi Project Team</b></p>
        ";

        $mail->send();
        echo "✅ Email sent successfully with a professional table-style PDF!";
    } catch (Exception $e) {
        echo "❌ Email could not be sent. Error: {$mail->ErrorInfo}";
    }

} else {
    echo "⚠️ Please submit the form from contact.php.";
}
?>
